export enum UserStatus {
    REGISTERED = "REGISTERED",
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    VERIFIED = "VERIFIED",
    WALLET_SETUP_PENDING = "WALLET_SETUP_PENDING",
    ACTIVE = "ACTIVE",
    REJECTED = "REJECTED",
    BLOCKED = "BLOCKED",
    TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
}
