export enum UserStatus {
    REGISTERED = "REGISTERED",
    VERIFICATION_PENDING = "VERIFICATION_PENDING",
    VERIFIED = "VERIFIED",
    WALLET_SETUP_PENDING = "WALLET_SETUP_PENDING",
    ACTIVE = "ACTIVE",
    REJECTED = "REJECTED",
    SUSPENDED = "SUSPENDED",
}
