import dotenv from 'dotenv';
import path from 'path';
import jwt from 'jsonwebtoken';

console.log("🔍 Starting Compatibility Verification...");

// 1. Simulate Auth Service (Port 4000)
console.log("\n--- Loading Auth Service Config ---");
const authEnvPath = path.resolve(__dirname, '../auth-service/.env');
const authConfig = dotenv.config({ path: authEnvPath });

if (authConfig.error) {
    console.error("❌ Failed to load auth-service .env");
    process.exit(1);
}

const authSecret = process.env.JWT_ACCESS_SECRET || process.env.JWT_SECRET;
console.log(`✅ Auth Service Secret loaded: ${authSecret?.substring(0, 5)}...`);


// 2. Simulate Unified API (Port 5000)
// We must clear the cache/process.env to load the next file cleanly or just read file directly, 
// but dotenv.config will mix them. Let's just manually read the file for safety or use override.
console.log("\n--- Loading Unified API Config ---");
const serviceEnvPath = path.resolve(__dirname, './hotel-search-service/.env');
// Clean env for simulation
delete process.env.JWT_ACCESS_SECRET;
delete process.env.JWT_SECRET;

const serviceConfig = dotenv.config({ path: serviceEnvPath, override: true });

if (serviceConfig.error) {
    console.error("❌ Failed to load hotel-search-service .env");
    process.exit(1);
}

const serviceSecret = process.env.JWT_ACCESS_SECRET || process.env.JWT_SECRET;
console.log(`✅ Unified API Secret loaded:  ${serviceSecret?.substring(0, 5)}...`);

// 3. Verification
console.log("\n--- Verification Results ---");
if (authSecret !== serviceSecret) {
    console.error("❌ MISMATCH DETECTED!");
    console.error(`Auth Service: ${authSecret}`);
    console.error(`Unified API:  ${serviceSecret}`);
    console.error("The token generated by Auth Service WILL fail on Unified API.");
} else {
    console.log("✅ SECRETS MATCH! The configuration is correct.");

    // 4. Runtime Test
    console.log("\n--- Runtime Token Simulation ---");
    const testPayload = { userId: "123", email: "test@test.com", role: "admin" };

    // Sign with Auth Service Secret
    const token = jwt.sign(testPayload, authSecret as string);
    console.log("Generated Token (Auth Service):", token.substring(0, 20) + "...");

    try {
        // Verify with Unified API Secret
        const decoded = jwt.verify(token, serviceSecret as string);
        console.log("✅ Token Verified Successfully by Unified API!");
        console.log("Decoded:", decoded);
    } catch (err) {
        console.error("❌ Token Verification Failed:", err);
    }
}
