export const CABIN_CLASSES = ['ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', 'FIRST'] as const;
export const FARE_TYPES = ['REGULAR', 'STUDENT', 'SENIOR_CITIZEN'] as const;
export const VALID_PAX_TYPES = ['ADULT', 'CHILD', 'INFANT'] as const;

export const ERROR_CODES = {
    INVALID_ROUTE_SEQUENCE: 'INVALID_ROUTE_SEQUENCE',
    INVALID_CABIN_CLASS: 'INVALID_CABIN_CLASS',
    INVALID_ADULT_COUNT: 'INVALID_ADULT_COUNT',
    INVALID_CHILD_COUNT: 'INVALID_CHILD_COUNT',
    INVALID_INFANT_COUNT: 'INVALID_INFANT_COUNT',
    MAX_PASSENGER_EXCEEDED: 'MAX_PASSENGER_EXCEEDED',
    INFANT_MORE_THAN_ADULT: 'INFANT_MORE_THAN_ADULT',
    EMPTY_ROUTE_INFOS: 'EMPTY_ROUTE_INFOS',
    INVALID_ROUTE_COUNT: 'INVALID_ROUTE_COUNT',
    INVALID_AIRPORT_CODE: 'INVALID_AIRPORT_CODE',
    INVALID_TRAVEL_DATE: 'INVALID_TRAVEL_DATE',
    SAME_ORIGIN_DESTINATION: 'SAME_ORIGIN_DESTINATION',
    DATE_NOT_ASCENDING: 'DATE_NOT_ASCENDING',
    DATE_TOO_FAR: 'DATE_TOO_FAR',
    INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
    PREFERRED_AIRLINE_LIMIT: 'PREFERRED_AIRLINE_LIMIT',
    INVALID_FARE_TYPE: 'INVALID_FARE_TYPE',
    CHILD_OR_INFANT_WITH_SPECIAL_FARE: 'CHILD_OR_INFANT_WITH_SPECIAL_FARE'
} as const;

export const MAX_PASSENGERS = 9;
export const MIN_ADULT = 1;
export const MAX_ROUTE_INFOS = 6;
export const MAX_PREFERRED_AIRLINES = 10;
export const AIRPORT_CODE_REGEX = /^[A-Z]{3}$/;
export const DATE_REGEX = /^\d{4}-\d{2}-\d{2}$/;