import { tripJackHmsClient, tripJackOmsClient } from "../clients/tripjack.client";
import { v4 as uuidv4 } from "uuid";

export class TripJackApiProvider {

    /**
     * POST /hms/v3/hotel/review
     * Validates the selected option. Returns bookingId needed for the Book API.
     * Must be called IMMEDIATELY before Book.
     *
     * Required fields per docs:
     *   correlationId, optionId, reviewHash, hid
     */
    async precheck(payload: any) {
        console.log("[TripJackProvider] Precheck payload received by provider:", JSON.stringify(payload, null, 2));

        const {
            hid: topHid,
            propertyID: topPropertyID,
            propertyId: topPropertyId,
            reviewHash: topReviewHash,
            correlationId: topCorrelationId,
            optionId: topOptionId,
            RoomSelection,
        } = payload;

        // Fallback extraction
        const hid = topHid || topPropertyId || topPropertyID || RoomSelection?.[0]?.hid || RoomSelection?.[0]?.tjHotelId || "";
        const reviewHash = topReviewHash || RoomSelection?.[0]?.reviewHash || RoomSelection?.[0]?.ReviewHash || RoomSelection?.[0]?.review_hash || "";
        const correlationId = topCorrelationId || RoomSelection?.[0]?.correlationId || RoomSelection?.[0]?.CorrelationId || RoomSelection?.[0]?._correlationId || "";
        const optionId = topOptionId || RoomSelection?.[0]?.optionId || RoomSelection?.[0]?.rateKey || RoomSelection?.[0]?.RoomSelectionKey || "";

        console.log(`[TripJackProvider] Extracted metadata - hid: ${hid}, reviewHash: ${reviewHash}, correlationId: ${correlationId}, optionId: ${optionId}`);

        // FIX #4: hid is required by TripJack Review API
        if (!optionId)      throw new Error("[TripJack Review] optionId is required");
        if (!reviewHash)    throw new Error("[TripJack Review] reviewHash is required");
        if (!hid)           throw new Error("[TripJack Review] hid is required");
        if (!correlationId) throw new Error("[TripJack Review] correlationId is required for v3 state tracking");

        const cleanHid = typeof hid === 'string' ? hid.replace("TJ:", "").trim() : hid;
        const isNumericHid = typeof cleanHid === 'string' && /^\d+$/.test(cleanHid);
        const finalHid = isNumericHid ? Number(cleanHid) : cleanHid;

        const tjPayload = {
            correlationId,
            optionId,
            reviewHash,
            hotelId: finalHid,
            hid: finalHid,
        };

        try {
            console.log(`[TripJack] Sending v3 Review Request to HMS:`, JSON.stringify(tjPayload, null, 2));
            const res = await tripJackHmsClient.post("/hms/v3/hotel/review", tjPayload);

            const data = res.data;
            
            // Check for internal TripJack errors (False Positives)
            if (data?.status?.success === false) {
                const errorMsg = data.errors?.[0]?.message || data.status?.description || "TripJack Review Internal Error";
                console.error(`[TripJack] Review Internal Failure: ${errorMsg}`, JSON.stringify(data.errors));
                throw {
                    response: {
                        status: 400,
                        data: data
                    }
                };
            }

            // bookingId is returned at top level — needed for the Book API
            const bookingId: string = data.bookingId || "";

            return {
                status: true,
                statusCode: 200,
                description: "TripJack Review Success",
                bookingId,          // ← expose at top level for the frontend
                body: data,
            };
        } catch (error: any) {
            const errorData = error.response?.data;
            const errorMessage = typeof errorData === 'string' 
                ? errorData.substring(0, 500) 
                : JSON.stringify(errorData || {}).substring(0, 500);
            console.error("[TripJack] Review Error:", error.response?.status, errorMessage);
            
            // Log full error for deep debugging if needed
            if (error.response?.data) {
                console.error("[TripJack-DEBUG] Full HMS Error Response:", JSON.stringify(error.response.data, null, 2));
            }

            // Return exactly what TJ sent us so frontend/test-script can see it
            throw {
                response: {
                    status: error.response?.status || 500,
                    data: error.response?.data || { description: error.message }
                }
            };
        }
    }

    /**
     * POST /oms/v3/hotel/book
     *
     * FIX #5: Completely rewritten to match TripJack v3 schema.
     * - bookingId comes from Review response (NOT generated by us)
     * - uses roomTravellerInfo (NOT roomsInfo/travellerInfo)
     * - requires deliveryInfo (emails, contacts, code)
     * - requires type: "HOTEL"
     * - paymentInfos present = Instant, absent = Hold
     */
    async commit(payload: any) {
        const {
            bookingId,         // from Review response — required
            roomTravellerInfo, // [{travellerInfo:[{ti,pt,fN,lN,pan?,pNum?}]}]
            deliveryInfo,      // {emails, contacts, code}
            paymentInfos,      // [{amount}] — include for Instant, omit for Hold
        } = payload;

        if (!bookingId)        throw new Error("[TripJack Book] bookingId (from Review) is required");
        if (!roomTravellerInfo?.length) throw new Error("[TripJack Book] roomTravellerInfo is required");

        const rawId = (payload.propertyId || payload.PropertyId || payload.hid || "").toString().replace("TJ:", "").trim();
        
        const tjPayload: any = {
            bookingId,
            type: "HOTEL",
            hotelId: rawId ? (Number.isNaN(Number(rawId)) ? rawId : Number(rawId)) : undefined,
            roomTravellerInfo,
            deliveryInfo: {
                emails:   deliveryInfo?.emails   || [],
                contacts: deliveryInfo?.contacts || [],
                code:     deliveryInfo?.code     || ["+91"],
            },
        };

        // Instant booking: include paymentInfos. Hold: omit.
        if (paymentInfos?.length) {
            tjPayload.paymentInfos = paymentInfos;
        }

        try {
            console.log(`[TripJack] Book Request:`, JSON.stringify(tjPayload, null, 2));
            const res = await tripJackOmsClient.post("/oms/v3/hotel/book", tjPayload);

            const data = res.data;

            // Check for internal TripJack errors (False Positives)
            if (data?.status?.success === false) {
                const errorMsg = data.errors?.[0]?.message || data.status?.description || "TripJack Book Internal Error";
                console.error(`[TripJack] Book Internal Failure: ${errorMsg}`, JSON.stringify(data.errors));
                throw {
                    response: {
                        status: 400,
                        data: data
                    }
                };
            }

            return {
                status: true,
                statusCode: 200,
                description: "TripJack Book Success",
                // TripJack Book API returns bookingId (e.g. "TJ202487947162")
                bookingId: data.bookingId || bookingId,
                body: data,
            };
        } catch (error: any) {
            const errorData = error.response?.data;
            const errorMessage = typeof errorData === 'string' 
                ? errorData.substring(0, 500) 
                : JSON.stringify(errorData || {}).substring(0, 500);
            console.error("[TripJack] Book Error:", error.response?.status, errorMessage);
            throw error;
        }
    }

    /**
     * POST /oms/v3/hotel/booking-details
     * Poll every 5s up to 180s after Book call.
     * Terminal states: SUCCESS, ON_HOLD, ABORTED, FAILED, CANCELLED
     */
    async getBookingDetails(bookingId: string): Promise<any> {
        try {
            const res = await tripJackOmsClient.post("/oms/v3/hotel/booking-details", { bookingId });
            return res.data;
        } catch (error: any) {
            const errorData = error.response?.data;
            const errorMessage = typeof errorData === 'string' 
                ? errorData.substring(0, 500) 
                : JSON.stringify(errorData || {}).substring(0, 500);
            console.error("[TripJack] GetBookingDetails Error:", errorMessage);
            throw error;
        }
    }

    /**
     * POST /oms/v3/hotel/cancel-booking/{bookingId}
     * FIX #6: TripJack cancel is POST, not DELETE. No request body needed.
     */
    async cancel(bookingId: string): Promise<any> {
        try {
            console.log(`[TripJack] Cancelling booking: ${bookingId}`);
            // FIX #6: POST (not DELETE)
            const res = await tripJackOmsClient.post(`/oms/v3/hotel/cancel-booking/${bookingId}`);
            return {
                status: true,
                statusCode: 200,
                description: "TripJack Cancel Success",
                body: res.data,
            };
        } catch (error: any) {
            const errorData = error.response?.data;
            const errorMessage = typeof errorData === 'string' 
                ? errorData.substring(0, 500) 
                : JSON.stringify(errorData || {}).substring(0, 500);
            console.error("[TripJack] Cancel Error:", errorMessage);
            throw error;
        }
    }

    /**
     * POST /oms/v3/hotel/amend-charges
     */
    async getAmendCharges(payload: any): Promise<any> {
        try {
            console.log(`[TripJack] Fetching Amendment Charges for: ${payload.bookingId}`);
            const res = await tripJackOmsClient.post("/oms/v3/hotel/amend-charges", payload);
            return res.data;
        } catch (error: any) {
            console.error("[TripJack] AmendCharges Error:", error.response?.data || error.message);
            throw error;
        }
    }

    /**
     * POST /oms/v3/hotel/amend
     * Commit the amendment request.
     */
    async amend(payload: any): Promise<any> {
        try {
            console.log(`[TripJack] Committing Amendment for: ${payload.bookingId}`);
            const res = await tripJackOmsClient.post("/oms/v3/hotel/amend", payload);
            return res.data;
        } catch (error: any) {
            console.error("[TripJack] Amend Commit Error:", error.response?.data || error.message);
            throw error;
        }
    }
}
